/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesNewRouteImport } from './routes/games/new'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'
import { Route as GamesGameIdRoundsRoundIdRouteImport } from './routes/games/$gameId.rounds/$roundId'
import { Route as GamesGameIdRoundsRoundIdPlayRouteImport } from './routes/games/$gameId.rounds/$roundId.play'
import { Route as GamesGameIdRoundsRoundIdBidRouteImport } from './routes/games/$gameId.rounds/$roundId.bid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoundsRoundIdRoute =
  GamesGameIdRoundsRoundIdRouteImport.update({
    id: '/rounds/$roundId',
    path: '/rounds/$roundId',
    getParentRoute: () => GamesGameIdRoute,
  } as any)
const GamesGameIdRoundsRoundIdPlayRoute =
  GamesGameIdRoundsRoundIdPlayRouteImport.update({
    id: '/play',
    path: '/play',
    getParentRoute: () => GamesGameIdRoundsRoundIdRoute,
  } as any)
const GamesGameIdRoundsRoundIdBidRoute =
  GamesGameIdRoundsRoundIdBidRouteImport.update({
    id: '/bid',
    path: '/bid',
    getParentRoute: () => GamesGameIdRoundsRoundIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRouteWithChildren
  '/games/new': typeof GamesNewRoute
  '/games/$gameId/rounds/$roundId': typeof GamesGameIdRoundsRoundIdRouteWithChildren
  '/games/$gameId/rounds/$roundId/bid': typeof GamesGameIdRoundsRoundIdBidRoute
  '/games/$gameId/rounds/$roundId/play': typeof GamesGameIdRoundsRoundIdPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRouteWithChildren
  '/games/new': typeof GamesNewRoute
  '/games/$gameId/rounds/$roundId': typeof GamesGameIdRoundsRoundIdRouteWithChildren
  '/games/$gameId/rounds/$roundId/bid': typeof GamesGameIdRoundsRoundIdBidRoute
  '/games/$gameId/rounds/$roundId/play': typeof GamesGameIdRoundsRoundIdPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRouteWithChildren
  '/games/new': typeof GamesNewRoute
  '/games/$gameId/rounds/$roundId': typeof GamesGameIdRoundsRoundIdRouteWithChildren
  '/games/$gameId/rounds/$roundId/bid': typeof GamesGameIdRoundsRoundIdBidRoute
  '/games/$gameId/rounds/$roundId/play': typeof GamesGameIdRoundsRoundIdPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/$gameId'
    | '/games/new'
    | '/games/$gameId/rounds/$roundId'
    | '/games/$gameId/rounds/$roundId/bid'
    | '/games/$gameId/rounds/$roundId/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/$gameId'
    | '/games/new'
    | '/games/$gameId/rounds/$roundId'
    | '/games/$gameId/rounds/$roundId/bid'
    | '/games/$gameId/rounds/$roundId/play'
  id:
    | '__root__'
    | '/'
    | '/games/$gameId'
    | '/games/new'
    | '/games/$gameId/rounds/$roundId'
    | '/games/$gameId/rounds/$roundId/bid'
    | '/games/$gameId/rounds/$roundId/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesGameIdRoute: typeof GamesGameIdRouteWithChildren
  GamesNewRoute: typeof GamesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/new': {
      id: '/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/rounds/$roundId': {
      id: '/games/$gameId/rounds/$roundId'
      path: '/rounds/$roundId'
      fullPath: '/games/$gameId/rounds/$roundId'
      preLoaderRoute: typeof GamesGameIdRoundsRoundIdRouteImport
      parentRoute: typeof GamesGameIdRoute
    }
    '/games/$gameId/rounds/$roundId/play': {
      id: '/games/$gameId/rounds/$roundId/play'
      path: '/play'
      fullPath: '/games/$gameId/rounds/$roundId/play'
      preLoaderRoute: typeof GamesGameIdRoundsRoundIdPlayRouteImport
      parentRoute: typeof GamesGameIdRoundsRoundIdRoute
    }
    '/games/$gameId/rounds/$roundId/bid': {
      id: '/games/$gameId/rounds/$roundId/bid'
      path: '/bid'
      fullPath: '/games/$gameId/rounds/$roundId/bid'
      preLoaderRoute: typeof GamesGameIdRoundsRoundIdBidRouteImport
      parentRoute: typeof GamesGameIdRoundsRoundIdRoute
    }
  }
}

interface GamesGameIdRoundsRoundIdRouteChildren {
  GamesGameIdRoundsRoundIdBidRoute: typeof GamesGameIdRoundsRoundIdBidRoute
  GamesGameIdRoundsRoundIdPlayRoute: typeof GamesGameIdRoundsRoundIdPlayRoute
}

const GamesGameIdRoundsRoundIdRouteChildren: GamesGameIdRoundsRoundIdRouteChildren =
  {
    GamesGameIdRoundsRoundIdBidRoute: GamesGameIdRoundsRoundIdBidRoute,
    GamesGameIdRoundsRoundIdPlayRoute: GamesGameIdRoundsRoundIdPlayRoute,
  }

const GamesGameIdRoundsRoundIdRouteWithChildren =
  GamesGameIdRoundsRoundIdRoute._addFileChildren(
    GamesGameIdRoundsRoundIdRouteChildren,
  )

interface GamesGameIdRouteChildren {
  GamesGameIdRoundsRoundIdRoute: typeof GamesGameIdRoundsRoundIdRouteWithChildren
}

const GamesGameIdRouteChildren: GamesGameIdRouteChildren = {
  GamesGameIdRoundsRoundIdRoute: GamesGameIdRoundsRoundIdRouteWithChildren,
}

const GamesGameIdRouteWithChildren = GamesGameIdRoute._addFileChildren(
  GamesGameIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesGameIdRoute: GamesGameIdRouteWithChildren,
  GamesNewRoute: GamesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
